version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ziwa
      MINIO_ROOT_PASSWORD: ziwadevpass
      MINIO_TRACE: console
    command: server --console-address ":9001" /data
    restart: unless-stopped

  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc config host add local http://minio:9000 ziwa ziwadevpass;
      mc mb local/ziwadev;
      mc anonymous set public local/ziwadev;
      "

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ziwadev
      POSTGRES_PASSWORD: ziwadevpass
      POSTGRES_DB: ziwadev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - "9092:9092"
    entrypoint: ["/entrypoint.sh"]
    command:
      - rpk
      - redpanda
      - start
      - --smp
      - '1'
      - --memory
      - '1G'
      - --reserve-memory
      - '0M'
      - --node-id
      - '0'
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092,OUTSIDE://localhost:9093
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:

  postgres-data:

