version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ziwa
      MINIO_ROOT_PASSWORD: ziwadevpass
      MINIO_TRACE: console
    command: server --console-address ":9001" /data
    restart: unless-stopped

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports: 
      - '8000:8000'
    command: start --log trace --user ziwa --pass ziwadevpass

  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - "9092:9092"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092,OUTSIDE://localhost:9093
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:
