version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ziwa
      MINIO_ROOT_PASSWORD: ziwadevpass
      MINIO_TRACE: console
    command: server --console-address ":9001" /data
    restart: unless-stopped
